### ISSUE TITLE
Missing Complete Details

### ISSUE THREAD

**Issue by Aryainguz** [praveenscience/TrailBlazer-ChitkaraUni#2] opened 2023-09-30 10:31 UTC
Hey Praveen, 

I attended your talk on open source trailblazing with open source and I feel I can add more details regarding the same as complete details might be missing

**Comment by praveenscience** [comment] 2023-09-30 10:48
This seems to be a dupe of #1.

**Closed as completed by praveenscience** 2023-09-30 10:48 UTC
